[features]
resolution = true
skip-lint = false

[programs.localnet]
zosh = "zosh4npemTuTj18MHgbn7NRihzMkTfgswTyP34LPaVx"

[programs.devnet]
zosh = "zosh4npemTuTj18MHgbn7NRihzMkTfgswTyP34LPaVx"

[programs.testnet]
zosh = "zosh4npemTuTj18MHgbn7NRihzMkTfgswTyP34LPaVx"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "testnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test -p zosh-program"

[test.validator]
url = "https://api.mainnet-beta.solana.com"

[[test.validator.clone]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"

[[test.validator.clone]]
address = "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"
