[package]
name = "zorch-sync"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
jsonrpsee-http-client.workspace = true
serde.workspace = true
solana-sdk.workspace = true
tokio.workspace = true
url.workspace = true
