[package]
name = "zosh-crypto"
version.workspace = true
edition.workspace = true
description = "Crypto primitives for the zosh bridge"

[dependencies]
anyhow.workspace = true
blake3.workspace = true
ed25519-dalek.workspace = true
