[package]
name = "zosh-runtime"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
crypto.workspace = true
postcard.workspace = true
tokio = { workspace = true, features = ["sync"] }
zcore.workspace = true
