[package]
name = "zosh-runtime"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
crypto.workspace = true
postcard.workspace = true
sync.workspace = true
zcore.workspace = true
