[package]
name = "zypher-runtime"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
bs58.workspace = true
postcard.workspace = true
reddsa.workspace = true
serde.workspace = true
solana-sdk.workspace = true
