[package]
name = "zorch-solana"
version.workspace = true
edition.workspace = true

[dependencies]
solana-client.workspace = true
solana-sdk.workspace = true
solana-program.workspace = true
anchor-lang.workspace = true
rand.workspace = true
borsh.workspace = true
spl-token.workspace = true
