[package]
name = "zosh-core"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
crypto.workspace = true
postcard.workspace = true
serde = { workspace = true, features = ["derive"] }
